spring:
  datasource:
    url: jdbc:mysql://localhost:3306/back
    username: ${DB_USERNAME:back_user}
    password: ${DB_PASSWORD:p@ssword}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# 해당 키는 로컬에서만 쓰이는 키 입니다.
jwt:
  secret: dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtaHMyNTY=
  access-token-expiration: 900000

logging:
  level:
    org.hibernate.SQL: debug